### ISSUE TITLE
Misc. bug: missing messages in JSON export via llama-server web UI

### ISSUE THREAD

**Issue by bughunter2** [ggml-org/llama.cpp#13552]
### Name and Version

$ ./llama-cli --version
version: 5359 (de4c07f9)
built with cc (Debian 12.2.0-14) 12.2.0 for x86_64-linux-gnu

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
llama-server --threads 10 --model ./Ministral-8B.gguf
```

### Problem description & steps to reproduce

When I use the web UI to download a conversation, a JSON file is downloaded, but I only seem to get the conversation's metadata, while the messages are *not* included.

```
{
  "id": "conv-1747263476494",
  "lastModified": 1747263485918,
  "currNode": 1747263476577,
  "name": "test"
}
```

### First Bad Commit

Not sure. I remember this worked fine with a fresh build from a month ago or so.

**edit:** It still worked in b5124 (bc091a4), which is when the 'Download' button was still located on the right, instead of in a context menu on the left.

**Comment by bughunter2** [comment]
@ngxson It seems your lovely webui revamp introduced this bug. Do you have some time to chime in? Cheers. 🙂

Posting the `git bisect` output here. It points to b5315 ([8c83449](https://github.com/ggml-org/llama.cpp/commit/8c83449cb780c201839653812681c3a4cf17feed)) as being the commit that caused the bug.

```
$ git bisect bad
8c83449cb780c201839653812681c3a4cf17feed is the first bad commit
commit 8c83449cb780c201839653812681c3a4cf17feed
Author: Xuan-Son Nguyen <son@huggingface.co>
Date:   Thu May 8 15:37:29 2025 +0200

    server : (webui) revamp the input area, plus many small UI improvements (#13365)
    
    * rework the input area
    
    * process selected file
    
    * change all icons to heroicons
    
    * fix thought process collapse
    
    * move conversation more menu to sidebar
    
    * sun icon --> moon icon
    
    * rm default system message
    
    * stricter upload file check, only allow image if server has mtmd
    
    * build it
    
    * add renaming
    
    * better autoscroll
    
    * build
    
    * add conversation group
    
    * fix scroll
    
    * extra context first, then user input in the end
    
    * fix <hr> tag
    
    * clean up a bit
    
    * build
    
    * add mb-3 for <pre>
    
    * throttle adjustTextareaHeight to make it less laggy
    
    * (nits) missing padding in sidebar
    
    * rm stray console log

 common/chat.cpp                                    |   4 +-
 tools/server/public/index.html.gz                  | Bin 1263424 -> 1289940 bytes
 tools/server/webui/package-lock.json               |  93 ++++++-
 tools/server/webui/package.json                    |   2 +
 tools/server/webui/src/App.tsx                     |   2 +
 tools/server/webui/src/Config.ts                   |   2 +-
 .../src/components/ChatInputExtraContextItem.tsx   |  92 +++++++
 tools/server/webui/src/components/ChatMessage.tsx  | 134 +++++-----
 tools/server/webui/src/components/ChatScreen.tsx   | 234 ++++++++++++-----
 tools/server/webui/src/components/Header.tsx       | 106 +-------
 .../webui/src/components/MarkdownDisplay.tsx       |  23 +-
 tools/server/webui/src/components/Sidebar.tsx      | 292 +++++++++++++++++++--
 .../webui/src/components/useChatExtraContext.tsx   | 174 ++++++++++++
 .../server/webui/src/components/useChatScroll.tsx  |  34 +++
 .../server/webui/src/components/useChatTextarea.ts |  53 ++--
 tools/server/webui/src/index.scss                  |   7 +-
 tools/server/webui/src/utils/app.context.tsx       |  26 +-
 tools/server/webui/src/utils/common.tsx            |  29 ++
 tools/server/webui/src/utils/llama-vscode.ts       |  33 ++-
 tools/server/webui/src/utils/misc.ts               |  75 +++++-
 tools/server/webui/src/utils/storage.ts            |  10 +
 tools/server/webui/src/utils/types.ts              |  36 ++-
 tools/server/webui/vite.config.ts                  |   1 +
 23 files changed, 1142 insertions(+), 320 deletions(-)
 create mode 100644 tools/server/webui/src/components/ChatInputExtraContextItem.tsx
 create mode 100644 tools/server/webui/src/components/useChatExtraContext.tsx
 create mode 100644 tools/server/webui/src/components/useChatScroll.tsx
```

**Comment by GaryMatthews** [comment]
Any word on this bug? i tried to backup my chat history but didn't verify they where complete before clearing all the data so i lost about 40+ conversations. also a tidy way to restore conversations from backups would be a nice feature.

**Comment by srogmann** [comment]
The pull request #14764 should address the missing `messages` list in the JSON export, which was omitted due to a commit in May. The updated code now includes the messages alongside the conversation metadata:

```javascript
                    const msgs = await StorageUtils.getMessages(conv.id);
                    const dict = { conv: conv, messages: msgs };
                    const conversationJson = JSON.stringify(dict, null, 2);
```
In my testing, the downloaded file now contains the `messages` array as expected.

**Comment by GaryMatthews** [comment]
Excellent! I copied and pasted this into the webgui and compiled it along with llama.cpp and the GUI now includes the exported messages. It would be nice to see some form of message history import system too. Id make these changes myself but i am not really a react developer and the extra complication of compiling web applications instead of just writing code that works in the browser out of the box is a place i refuse to go.

**Comment by bughunter2** [comment]
@srogmann: Can confirm. This works perfectly for me. 🙂 Hopefully your PR gets reviewed and accepted soon. 🤞

**Comment by srogmann** [comment]
@GaryMatthews I also needed a way to export all conversations, so I implemented one here: https://github.com/srogmann/llama.cpp/tree/feature/import_export_all.
However, in #14764 I learned that there are plans to migrate the frontend to Svelte, so I decided not to open a pull request for now.

**Comment by TFWol** [comment]
Came here after I stumbled across the same issue.

I'm surprised this is still broken...
