### ISSUE TITLE
Misc. bug: --cache-reuse no longer seems to be caching prompt prefixes

### ISSUE THREAD

**Issue by ghnp5** [ggml-org/llama.cpp#14113]
### Name and Version

**Affected:**
Version at commit: https://github.com/ggml-org/llama.cpp/commit/b7a17463ec190aeee7b9077c606c910fb4688b84

**Not affected:**
Version at commit: https://github.com/ggml-org/llama.cpp/commit/c6a2c9e7411f54b0770b319740561bbd6a2ebd27

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell

```

### Problem description & steps to reproduce

I had open this bug in `oobabooga/text-generation-webui`: https://github.com/oobabooga/text-generation-webui/issues/7060

The issue being that prompt prefixes were no longer being used in the following requests.

I confirmed that `--cache-reuse 1` was being passed on, so that wasn't the issue.
After reverting to a the version of the WebUI, the prompts started to be cached again.

So, this seems to point to being a bug with `llama.cpp`.

### First Bad Commit

It looks like there may have been a commit between https://github.com/ggml-org/llama.cpp/commit/c6a2c9e7411f54b0770b319740561bbd6a2ebd27 and https://github.com/ggml-org/llama.cpp/commit/b7a17463ec190aeee7b9077c606c910fb4688b84 that broke `--cache-reuse`, or that changed its behavior.

### Relevant log output

```shell

```

**Comment by ggerganov** [comment]
Provide repro steps using `llama-server`.

**Comment by ghnp5** [comment]
Hello,

Thank you for your reply. I use the `oobabooga/text-generation-webui` project, which bundles a snapshot of `llama.cpp` (the commits I mentioned above),

and, from what I saw, this is the command it runs:

```
llama-server --model user_data/models/gemma-3-12b-it-qat-UD-Q6_K_XL.guff --ctx-size 32768 --gpu-layers 49 --batch-size 256 --port 60033 --no-webui --threads 10 --threads-batch 10 --rope-freq-scale 0.125 --rope-freq-base 1000000.0 --cache-reuse 1
```

The model can be downloaded from: https://huggingface.co/unsloth/gemma-3-12b-it-qat-GGUF/tree/main

I confirm `--cache-reuse 1` is present in the parameters, when the cache isn't working.

I don't know how exactly a Chat Completion call is made to `llama-server`, but basically, if I make two chat-instruct calls, where the first 1000 characters or so are exactly the same, the prompt will be processed from byte 0, when using the affected commits I mentioned above.

I'm not providing the `cache_prompt` parameter, so it should default to `true`.

I hope this helps!

**Comment by ggerganov** [comment]
The `--cache-reuse` parameter is not relevant for this case.

SWA models like Gemma could exhibit the problem that you describe, but I am fairly certain that I fixed this in https://github.com/ggml-org/llama.cpp/pull/13833. Unless you can provide repro steps, I would assume this is a problem in the oobabooga project.

**Comment by ghnp5** [comment]
Thank you. This same Gemma model that I'm using works when I use the `llama-server` version at https://github.com/ggml-org/llama.cpp/commit/c6a2c9e7411f54b0770b319740561bbd6a2ebd27

Apologies - I'm confused why `--cache-reuse` is not relevant. Isn't this (together with `cache_prompt: true`) what prevents the prompt prefix from being re-processed on subsequent requests that share the same prefix?

If I don't include `--cache-reuse` in the parameters, then the prompt will always be fully processed from the beginning, even on the version that works for me.

> Unless you can provide repro steps

Please let me know exactly what do you need, for repro steps.

**Comment by ghnp5** [comment]
@ggerganov - This is still happening when using the version at https://github.com/ggml-org/llama.cpp/tree/90083283ec254fa8d33897746dea229aee401b37

It appears that the fix from https://github.com/ggml-org/llama.cpp/pull/14163 did not fix the cache issue.

Thank you.
