### ISSUE TITLE
Compile bug: vulkan-shaders-gen is installed into the build location instead of $PREFIX/bin/vulkan-shaders-gen

### ISSUE THREAD

**Issue by yurivict** [ggml-org/llama.cpp#14190]
### Git commit

5664

### Operating systems

BSD

### GGML backends

CPU

### Problem description & steps to reproduce

vulkan-shaders-gen is installed into /usr/ports/misc/llama-cpp/work/.build/bin/vulkan-shaders-gen imstead of /usr/local/bin/vulkan-shaders-gen

### Compile command

```shell
n/a
```

### Relevant log output

```shell
n/a
```

**Comment by 0cc4m** [comment]
`vulkan-shaders-gen` is a binary that compiles all of the Vulkan shaders during the llama.cpp build process, it is not required afterwards. The behaviour of not installing it globally seems correct to me.

**Comment by yurivict** [comment]
> The behaviour of not installing it globally seems correct to me.

But the behavior is different: it installs it back into the same build folder during  ```"make install"```.
Instead it shouldn't install it at all.

**Comment by 0cc4m** [comment]
That makes sense. @bandoti any thoughts?

**Comment by mtmcp** [comment]
@yurivict Thanks for reporting the issue.

As part of #14179 the ExternalProject_Add command was "normalized" so that it would install to the build directory so it can work with both multi-configuration and single-configuration generators. I actually tried to use the regular build directory (skipping the install step) but had a couple hiccups with the various generators paths.

The intent, however, is that the "installed" vulkan-shaders-gen is done for the build (as it is an internal detail) and not included in the overall installed targets with a top-level "make install".

I'm thinking the issue is because the _*-build_ and _*-install_ targets are explicitly added here (although that was more-or-less the previous behavior).
```
        DEPENDS ${_ggml_vk_shader_files}
                vulkan-shaders-gen
                vulkan-shaders-gen-build
                vulkan-shaders-gen-install
```

If you would provide the command-line used to configure, build, and install that will be helpful. Thanks.

**Comment by yurivict** [comment]
The full configure command:
cd /usr/ports/misc/llama-cpp/work/.build; /usr/bin/env -i HOME=/usr/ports/misc/llama-cpp/work  MACHINE_ARCH=amd64  PWD="${PWD}"  GIT_CEILING_DIRECTORIES=/usr/ports/misc/llama-cpp/work  __MAKE_CONF=/nonexistent OSVERSION=1402504 PATH=/usr/local/libexec/ccache:/usr/ports/misc/llama-cpp/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin TERM=xterm-256color PYTHON="/usr/local/bin/python3.11" XDG_DATA_HOME=/usr/ports/misc/llama-cpp/work  XDG_CONFIG_HOME=/usr/ports/misc/llama-cpp/work  XDG_CACHE_HOME=/usr/ports/misc/llama-cpp/work/.cache  HOME=/usr/ports/misc/llama-cpp/work PATH=/usr/local/libexec/ccache:/usr/ports/misc/llama-cpp/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/usr/ports/misc/llama-cpp/work/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig SHELL=/bin/sh CONFIG_SHELL=/bin/sh CMAKE_PREFIX_PATH="/usr/local" CCACHE_DIR="/var/ccache" /usr/local/bin/cmake  -DLLAMA_CURL:BOOL=true -DLLAMA_BUILD_EXAMPLES:BOOL=true -DGGML_VULKAN:BOOL=true -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DNDEBUG"  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -DNDEBUG"  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_AUTOGEN_PARALLEL:STRING="7"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DGGML_NATIVE:BOOL=OFF -DFREEBSD_ALLOW_ADVANCED_CPU_FEATURES:BOOL=OFF -DLLAMA_BUILD_TESTS:BOOL=OFF -GNinja -DPython_ADDITIONAL_VERSIONS=3.11 -DPython_EXECUTABLE:FILEPATH="/usr/local/bin/python3.11" -DPython3_EXECUTABLE:FILEPATH="/usr/local/bin/python3.11" -DBOOST_PYTHON_SUFFIX:STRING=311 /usr/ports/misc/llama-cpp/work/llama.cpp-b5684

**Comment by yurivict** [comment]
I am building the the FreeBSD port directory.
It used to break in the install target, but now it breaks in the build target:

It fails like this in the build target:

[ 50% 1/2] Building CXX object CMakeFiles/vulkan-shaders-gen.dir/vulkan-shaders-gen.cpp.o
[100% 2/2] Linking CXX executable vulkan-shaders-gen
[ 25% 44/175] cd /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/vulkan-shaders-gen-prefix/src/vulkan-shaders-gen-build && /usr/local/bin/cmake --install . --config Release && /usr/local/bin/cmake -E touch /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/vulkan-shaders-gen-prefix/src/vulkan-shaders-gen-stamp/vulkan-shaders-gen-install
-- Installing: /usr/ports/misc/llama-cpp/work/stage/usr/ports/misc/llama-cpp/work/.build/Release/./vulkan-shaders-gen
[ 25% 45/175] cd /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan && /usr/local/bin/cmake -E make_directory /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/CMakeFiles && /usr/local/bin/cmake -E touch /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/CMakeFiles/vulkan-shaders-gen-complete && /usr/local/bin/cmake -E touch /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/vulkan-shaders-gen-prefix/src/vulkan-shaders-gen-stamp/vulkan-shaders-gen-done
[ 26% 46/175] cd /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan && /usr/ports/misc/llama-cpp/work/.build/Release/vulkan-shaders-gen --glslc /usr/local/bin/glslc --input-dir /usr/ports/misc/llama-cpp/work/llama.cpp-b5684/ggml/src/ggml-vulkan/vulkan-shaders --output-dir /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/vulkan-shaders.spv --target-hpp /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/ggml-vulkan-shaders.hpp --target-cpp /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/ggml-vulkan-shaders.cpp --no-clean
FAILED: ggml/src/ggml-vulkan/ggml-vulkan-shaders.hpp ggml/src/ggml-vulkan/ggml-vulkan-shaders.cpp /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/ggml-vulkan-shaders.hpp /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/ggml-vulkan-shaders.cpp 
cd /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan && /usr/ports/misc/llama-cpp/work/.build/Release/vulkan-shaders-gen --glslc /usr/local/bin/glslc --input-dir /usr/ports/misc/llama-cpp/work/llama.cpp-b5684/ggml/src/ggml-vulkan/vulkan-shaders --output-dir /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/vulkan-shaders.spv --target-hpp /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/ggml-vulkan-shaders.hpp --target-cpp /usr/ports/misc/llama-cpp/work/.build/ggml/src/ggml-vulkan/ggml-vulkan-shaders.cpp --no-clean
/bin/sh: /usr/ports/misc/llama-cpp/work/.build/Release/vulkan-shaders-gen: not found
ninja: build stopped: subcommand failed.

**Comment by yurivict** [comment]
AFAIK the cmake's install instruction always installs the file during "make install" which is not what is desired.

You should remove the install instruction, and add the cmake's [add_dependencies](https://cmake.org/cmake/help/latest/command/add_dependencies.html) instruction.

**Comment by mtmcp** [comment]
@yurivict Would it be possible for you to test against the branch [bandoti:cmake-vulkan-shaders-gen-install](https://github.com/bandoti/llama.cpp/tree/cmake-vulkan-shaders-gen-install) that is used in #14226?

I think this change should fix the issue, but it would be great if you are able to verify it works on FreeBSD since I don't currently use that system.

**Comment by yurivict** [comment]
The revision 90ccac216290488aa79ae571b328d9aea6e6c584 still fails in "make build".
