### ISSUE TITLE
Misc. bug: llama-fit-params stuck in infinite loop

### ISSUE THREAD

**Issue by jettoblack** [ggml-org/llama.cpp#18337]
### Name and Version

version: 7524 (5ee4e43f2)
built with GNU 13.3.0 for Linux x86_64

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

Other (Please specify in the next section)

### Command line

```shell
llama-fit-params -hf unsloth/GLM-4.7-GGUF:IQ2_XXS -c 65536
```

### Problem description & steps to reproduce

On a host with 4x 3090 24GB, 1x 5060Ti 16GB, 64GB host RAM

Output without --verbose, here's where it gets stuck and stops logging:
```
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 5 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 1: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 2: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 3: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 4: NVIDIA GeForce RTX 5060 Ti, compute capability 12.0, VMM: yes
common_download_file_single_online: using cached file: /home/jasonl/.cache/llama.cpp/unsloth_GLM-4.7-GGUF_UD-IQ2_XXS_GLM-4.7-UD-IQ2_XXS-00001-of-00003.gguf
common_download_file_single_online: using cached file: /home/jasonl/.cache/llama.cpp/unsloth_GLM-4.7-GGUF_UD-IQ2_XXS_GLM-4.7-UD-IQ2_XXS-00002-of-00003.gguf
common_download_file_single_online: using cached file: /home/jasonl/.cache/llama.cpp/unsloth_GLM-4.7-GGUF_UD-IQ2_XXS_GLM-4.7-UD-IQ2_XXS-00003-of-00003.gguf
build: 7524 (5ee4e43f2) with GNU 13.3.0 for Linux x86_64
llama_params_fit_impl: projected memory use with initial parameters [MiB]:
llama_params_fit_impl:   - CUDA0 (NVIDIA GeForce RTX 3090)   :  24124 total,  27958 used,   4099 deficit
llama_params_fit_impl:   - CUDA1 (NVIDIA GeForce RTX 3090)   :  24124 total,  30479 used,   6620 deficit
llama_params_fit_impl:   - CUDA2 (NVIDIA GeForce RTX 3090)   :  24124 total,  29214 used,   5355 deficit
llama_params_fit_impl:   - CUDA3 (NVIDIA GeForce RTX 3090)   :  24115 total,  28974 used,   5131 deficit
llama_params_fit_impl:   - CUDA4 (NVIDIA GeForce RTX 5060 Ti):  15848 total,  18177 used,   2468 deficit
llama_params_fit_impl: projected to use 134804 MiB of device memory vs. 112335 MiB of free device memory
llama_params_fit_impl: cannot fulfill margin of 1024 MiB on all devices, need to use 28796 MiB less in total
llama_params_fit_impl: context size set by user to 65536 -> no change
llama_params_fit_impl: with only dense weights in device memory there is a total surplus of 71665 MiB
llama_params_fit_impl: filling dense-only layers back-to-front:
llama_params_fit_impl:   - CUDA4 (NVIDIA GeForce RTX 5060 Ti): 41 layers,  14446 MiB used,   1262 MiB free
llama_params_fit_impl:   - CUDA3 (NVIDIA GeForce RTX 3090)   : 53 layers,  18698 MiB used,   5143 MiB free
llama_params_fit_impl:   - CUDA2 (NVIDIA GeForce RTX 3090)   :  0 layers,      0 MiB used,  23859 MiB free
llama_params_fit_impl:   - CUDA1 (NVIDIA GeForce RTX 3090)   :  0 layers,      0 MiB used,  23859 MiB free
llama_params_fit_impl:   - CUDA0 (NVIDIA GeForce RTX 3090)   :  0 layers,   1032 MiB used,  22826 MiB free
llama_params_fit_impl: converting dense-only layers to full layers and filling them front-to-back with overflow to next device/system memory:
llama_params_fit_impl:   - CUDA0 (NVIDIA GeForce RTX 3090)   : 18 layers ( 1 overflowing),  22833 MiB used,   1025 MiB free
llama_params_fit_impl:   - CUDA1 (NVIDIA GeForce RTX 3090)   : 15 layers ( 1 overflowing),  22430 MiB used,   1428 MiB free
llama_params_fit_impl:   - CUDA2 (NVIDIA GeForce RTX 3090)   : 15 layers ( 1 overflowing),  22657 MiB used,   1201 MiB free
```

### Relevant log output

```shell
When running with --verbose, the output log grows seemingly forever, or at least as long as I was willing to let it run. Here's ~ 200MB worth zipped:

[fit.txt.gz](https://github.com/user-attachments/files/24321672/fit.txt.gz)
```

**Comment by JohannesGaessler** [comment]
I think there is a problem with uploading files in text blocks. When I copy-paste the link I get "Not Found". Can you upload the file again?

**Comment by jettoblack** [comment]
[fit.txt.gz](https://github.com/user-attachments/files/24351570/fit.txt.gz)

Trying the attachment again.

I can reproduce the issue with other models and with certain context sizes, but changing the context size by a few K often fixes it, e.g. 65536 and 80000 will reproduce the problem, but 72000 will work.

**Comment by JohannesGaessler** [comment]
Should be fixed by https://github.com/ggml-org/llama.cpp/pull/18415 , please confirm.

**Comment by jettoblack** [comment]
@JohannesGaessler Sorry to say after trying this fix I'm still experiencing the problem, using build 7565 (382808c14) which includes PR #18415 .

Here's a verbose log of one that still causes an infinite loop:

`build/bin/llama-server -hf unsloth/MiniMax-M2.1-GGUF:Q3_K_XL -c 131072 --host 0.0.0.0 --jinja --verbose`

[fit_7565.txt.gz](https://github.com/user-attachments/files/24363893/fit_7565.txt.gz)

Here's where that command gets stuck without --verbose:
```
llama_params_fit_impl: converting dense-only layers to full layers and filling them front-to-back with overflow to next d
evice/system memory:
llama_params_fit_impl:   - CUDA0 (NVIDIA GeForce RTX 3090)   : 11 layers ( 1 overflowing),  22408 MiB used,   1450 MiB fr
ee
llama_params_fit_impl:   - CUDA1 (NVIDIA GeForce RTX 3090)   : 11 layers ( 1 overflowing),  22473 MiB used,   1385 MiB fr
ee
llama_params_fit_impl:   - CUDA2 (NVIDIA GeForce RTX 3090)   : 11 layers ( 1 overflowing),  22785 MiB used,   1073 MiB fr
ee
```

As I mentioned I can reproduce the problem with various models and context sizes. 

Here's a different, possibly unrelated issue where changing the context size to 196608 (the max size for this model) avoids the infinite loop, but the resulting fit fails at load time, it is trying to load > 17GB onto the 16GB GPU:

`build/bin/llama-server -hf unsloth/MiniMax-M2.1-GGUF:Q3_K_XL --host 0.0.0.0 --jinja -c 196608`

```
llama_params_fit_impl: projected memory use with initial parameters [MiB]:
llama_params_fit_impl:   - CUDA0 (NVIDIA GeForce RTX 3090)   :  24124 total,  34256 used,  10397 deficit
llama_params_fit_impl:   - CUDA1 (NVIDIA GeForce RTX 3090)   :  24124 total,  33138 used,   9279 deficit
llama_params_fit_impl:   - CUDA2 (NVIDIA GeForce RTX 3090)   :  24124 total,  30700 used,   6841 deficit
llama_params_fit_impl:   - CUDA3 (NVIDIA GeForce RTX 3090)   :  24115 total,  33305 used,   9463 deficit
llama_params_fit_impl:   - CUDA4 (NVIDIA GeForce RTX 5060 Ti):  15848 total,  18283 used,   2574 deficit
llama_params_fit_impl: projected to use 149685 MiB of device memory vs. 111128 MiB of free device memory
llama_params_fit_impl: cannot fulfill margin of 1024 MiB on all devices, need to use 43677 MiB less in total
llama_params_fit_impl: context size set by user to 196608 -> no change
llama_params_fit_impl: with only dense weights in device memory there is a total surplus of 53844 MiB
llama_params_fit_impl: filling dense-only layers back-to-front:
llama_params_fit_impl:   - CUDA4 (NVIDIA GeForce RTX 5060 Ti): 18 layers,  14421 MiB used,   1287 MiB free
llama_params_fit_impl:   - CUDA3 (NVIDIA GeForce RTX 3090)   : 28 layers,  22489 MiB used,   1352 MiB free
llama_params_fit_impl:   - CUDA2 (NVIDIA GeForce RTX 3090)   : 17 layers,  14149 MiB used,   9709 MiB free
llama_params_fit_impl:   - CUDA1 (NVIDIA GeForce RTX 3090)   :  0 layers,      0 MiB used,  23859 MiB free
llama_params_fit_impl:   - CUDA0 (NVIDIA GeForce RTX 3090)   :  0 layers,   1149 MiB used,  22709 MiB free
llama_params_fit_impl: converting dense-only layers to full layers and filling them front-to-back with overflow to next device/system memory:
llama_params_fit_impl:   - CUDA0 (NVIDIA GeForce RTX 3090)   :  9 layers ( 0 overflowing),  22144 MiB used,   1714 MiB free
llama_params_fit_impl:   - CUDA1 (NVIDIA GeForce RTX 3090)   : 10 layers ( 1 overflowing),  22588 MiB used,   1270 MiB free
llama_params_fit_impl:   - CUDA2 (NVIDIA GeForce RTX 3090)   : 10 layers ( 1 overflowing),  22409 MiB used,   1449 MiB free
llama_params_fit_impl:   - CUDA3 (NVIDIA GeForce RTX 3090)   : 16 layers (11 overflowing),  21910 MiB used,   1931 MiB free
llama_params_fit: successfully fit params to free device memory
[...]
load_tensors: loading model tensors, this can take a while... (mmap = true)
ggml_backend_cuda_buffer_type_alloc_buffer: allocating 17762.63 MiB on device 4: cudaMalloc failed: out of memory
alloc_tensor_range: failed to allocate CUDA4 buffer of size 18625472512
llama_model_load: error loading model: unable to allocate CUDA4 buffer
```

Verbose log for that one:

[fit_7565_toobig.txt.gz](https://github.com/user-attachments/files/24363917/fit_7565_toobig.txt.gz)

Let me know if that should be written up as a separate issue.

**Comment by JohannesGaessler** [comment]
Sorry, I was too hasty with the other fix. Can you confirm whether or not this works correctly? https://github.com/ggml-org/llama.cpp/pull/18494

**Comment by jettoblack** [comment]
> Sorry, I was too hasty with the other fix. Can you confirm whether or not this works correctly? [#18494](https://github.com/ggml-org/llama.cpp/pull/18494)

Unfortunately this did not fix either of the above cases for me. 

Here's a new verbose log for the infinite loop, just in case something changed enough to provide a clue.

[15182a1.txt.gz](https://github.com/user-attachments/files/24389590/15182a1.txt.gz)

Thanks for looking into it.

**Comment by aphipps** [comment]
This also happens to me when I use the default context length, which may just be too big to fit in my GPU. #18494 did not improve things.  Running with "fit off" results in an immediate error, while the default "fit on" just goes into an endless loop. Manually reducing the context length helped.

**Comment by JohannesGaessler** [comment]
It seems there were 2 separate bugs, can you re-test the PR I linked?

**Comment by jettoblack** [comment]
> It seems there were 2 separate bugs, can you re-test the PR I linked?

@JohannesGaessler efeb1eb is still getting stuck for me. Here is another verbose log:

[efeb1eb.txt.gz](https://github.com/user-attachments/files/24420429/efeb1eb.txt.gz)

Without --verbose, still stuck in the same place I think:
```
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 5 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 1: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 2: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 3: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 4: NVIDIA GeForce RTX 5060 Ti, compute capability 12.0, VMM: yes
common_download_file_single_online: using cached file: /home/jasonl/.cache/llama.cpp/unsloth_MiniMax-M2.1-GGUF_UD-Q3_K_XL_MiniMax-M2.1-UD-Q3_K_XL-00001-of-00003.gguf
common_download_file_single_online: using cached file: /home/jasonl/.cache/llama.cpp/unsloth_MiniMax-M2.1-GGUF_UD-Q3_K_XL_MiniMax-M2.1-UD-Q3_K_XL-00003-of-00003.gguf
common_download_file_single_online: using cached file: /home/jasonl/.cache/llama.cpp/unsloth_MiniMax-M2.1-GGUF_UD-Q3_K_XL_MiniMax-M2.1-UD-Q3_K_XL-00002-of-00003.gguf
main: n_parallel is set to auto, using n_parallel = 4 and kv_unified = true
build: 7585 (efeb1ebc4) with GNU 13.3.0 for Linux x86_64
system info: n_threads = 12, n_threads_batch = 12, total_threads = 24

system_info: n_threads = 12 (n_threads_batch = 12) / 24 | CUDA : ARCHS = 860,890,1200 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | BLACKWELL_NATIVE_FP4 = 1 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | BMI2 = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 | 

init: using 23 threads for HTTP server
start: binding port with default address family
main: loading model
srv    load_model: loading model '/home/jasonl/.cache/llama.cpp/unsloth_MiniMax-M2.1-GGUF_UD-Q3_K_XL_MiniMax-M2.1-UD-Q3_K_XL-00001-of-00003.gguf'
common_init_result: fitting params to device memory, for bugs during this step try to reproduce them with -fit off, or provide --verbose logs if the bug only occurs with -fit on
llama_params_fit_impl: projected memory use with initial parameters [MiB]:
llama_params_fit_impl:   - CUDA0 (NVIDIA GeForce RTX 3090)   :  24124 total,  30096 used,   6237 deficit
llama_params_fit_impl:   - CUDA1 (NVIDIA GeForce RTX 3090)   :  24124 total,  29298 used,   5439 deficit
llama_params_fit_impl:   - CUDA2 (NVIDIA GeForce RTX 3090)   :  24124 total,  27116 used,   3257 deficit
llama_params_fit_impl:   - CUDA3 (NVIDIA GeForce RTX 3090)   :  24115 total,  29465 used,   5623 deficit
llama_params_fit_impl:   - CUDA4 (NVIDIA GeForce RTX 5060 Ti):  15848 total,  16235 used,    526 deficit
llama_params_fit_impl: projected to use 132213 MiB of device memory vs. 111128 MiB of free device memory
llama_params_fit_impl: cannot fulfill margin of 1024 MiB on all devices, need to use 26205 MiB less in total
llama_params_fit_impl: context size set by user to 131072 -> no change
llama_params_fit_impl: with only dense weights in device memory there is a total surplus of 70018 MiB
llama_params_fit_impl: filling dense-only layers back-to-front:
llama_params_fit_impl:   - CUDA4 (NVIDIA GeForce RTX 5060 Ti): 23 layers,  14253 MiB used,   1455 MiB free
llama_params_fit_impl:   - CUDA3 (NVIDIA GeForce RTX 3090)   : 40 layers,  22000 MiB used,   1841 MiB free
llama_params_fit_impl:   - CUDA2 (NVIDIA GeForce RTX 3090)   :  0 layers,      0 MiB used,  23859 MiB free
llama_params_fit_impl:   - CUDA1 (NVIDIA GeForce RTX 3090)   :  0 layers,      0 MiB used,  23859 MiB free
llama_params_fit_impl:   - CUDA0 (NVIDIA GeForce RTX 3090)   :  0 layers,   1149 MiB used,  22709 MiB free
llama_params_fit_impl: converting dense-only layers to full layers and filling them front-to-back with overflow to next device/system memory:
llama_params_fit_impl:   - CUDA0 (NVIDIA GeForce RTX 3090)   : 11 layers ( 1 overflowing),  22408 MiB used,   1450 MiB free
llama_params_fit_impl:   - CUDA1 (NVIDIA GeForce RTX 3090)   : 11 layers ( 1 overflowing),  22473 MiB used,   1385 MiB free
llama_params_fit_impl:   - CUDA2 (NVIDIA GeForce RTX 3090)   : 11 layers ( 1 overflowing),  22785 MiB used,   1073 MiB free
```

**Comment by JohannesGaessler** [comment]
I pushed a new version, can you re-test?

**Comment by aphipps** [comment]
@JohannesGaessler for me, it fixes the infinite loop, thank you. I now get a floating point exception abort - possibly unrelated, but it works ok with fit off and specifying parameters.

[log-before.txt](https://github.com/user-attachments/files/24425315/log-before.txt)

[log-after.txt](https://github.com/user-attachments/files/24425317/log-after.txt)

**Comment by JohannesGaessler** [comment]
Okay, it seems that the code found the correct assignment of tensors to GPUs and then crashed because I accidentally introduced a new bug where the loop bounds were wrong. The new version I pushed is hopefully the last one we need.

**Comment by aphipps** [comment]
@JohannesGaessler working for me now, thanks! 

[log-new.txt](https://github.com/user-attachments/files/24437707/log-new.txt)

**Comment by aphipps** [comment]
@JohannesGaessler while I'm no longer seeing an infinite loop and it works for a small model, with a larger model I get a CUDA OOM and then a seg fault.  Probably a separate issue but wanted to note it just in case.
[log-glm47.txt](https://github.com/user-attachments/files/24437753/log-glm47.txt)

**Comment by JohannesGaessler** [comment]
The bug you're describing is related, I had simplified one of the fixes in an incorrect way so some tensors were incorrectly put onto the last GPU, causing an OOM. Please re-test.

**Comment by aphipps** [comment]
@JohannesGaessler thank you, works now 👍
