### ISSUE TITLE
Compile bug: CUDA build for  mmq breaks for compute capability 120

### ISSUE THREAD

**Issue by mramendi** [ggml-org/llama.cpp#18363]
### Git commit

$ git rev-parse HEAD
c54bba869da97feeaf788cac499679c9a9ff9fea

### Operating systems

Linux

### GGML backends

CUDA

### Problem description & steps to reproduce

When CUDA compute 120 is enabled, the build breaks on mmq; see commands and logs in the fields below

### First Bad Commit

https://github.com/ggml-org/llama.cpp/commit/c8a2417d7b65705231eeb5b4080d3e0428c9c5d2

### Compile command

```shell
cmake -B build -DGGML_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES="80;86;90;120" -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/cuda/lib64/stubs" -DCMAKE_SHARED_LINKER_FLAGS="-L/usr/local/cuda/lib64/stubs"

make --build build --config Release -j 6
```

### Relevant log output

```shell
27%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-q4_0.cu.o
ptxas /tmp/tmpxft_00007d6d_00000000-6_mmq-instance-mxfp4.compute_120.ptx, line 1025; error   : Instruction 'mma with block scale' not supported on .target 'sm_120'
ptxas /tmp/tmpxft_00007d6d_00000000-6_mmq-instance-mxfp4.compute_120.ptx, line 1025; error   : Feature '.kind::mxf4' not supported on .target 'sm_120'
ptxas /tmp/tmpxft_00007d6d_00000000-6_mmq-instance-mxfp4.compute_120.ptx, line 1025; error   : Feature '.block_scale' not supported on .target 'sm_120'
ptxas /tmp/tmpxft_00007d6d_00000000-6_mmq-instance-mxfp4.compute_120.ptx, line 1025; error   : Feature '.scale_vec::2X' not supported on .target 'sm_120'
ptxas /tmp/tmpxft_00007d6d_00000000-6_mmq-instance-mxfp4.compute_120.ptx, line 1039; error   : Instruction 'mma with block scale' not supported on .target 'sm_120'
(many, many other similar lines)
```

**Comment by am17an** [comment]
You need to add `120a`, or use #18361

**Comment by raziel2001au** [comment]
I just updated to the latest code, I'm getting very similar compile errors for sm_121:
```
ptxas /tmp/tmpxft_000064a1_00000000-7_mmq-instance-mxfp4.ptx, line 112320; error   : Feature '.block_scale' not supported on .target 'sm_121'                                                                                                       
ptxas /tmp/tmpxft_000064a1_00000000-7_mmq-instance-mxfp4.ptx, line 112320; error   : Feature '.scale_vec::2X' not supported on .target 'sm_121'                                                                                                     
ptxas /tmp/tmpxft_000064a1_00000000-7_mmq-instance-mxfp4.ptx, line 112334; error   : Instruction 'mma with block scale' not supported on .target 'sm_121'                                                                                           
ptxas /tmp/tmpxft_000064a1_00000000-7_mmq-instance-mxfp4.ptx, line 112334; error   : Feature '.kind::mxf4' not supported on .target 'sm_121'                                                                                                        
ptxas /tmp/tmpxft_000064a1_00000000-7_mmq-instance-mxfp4.ptx, line 112334; error   : Feature '.block_scale' not supported on .target 'sm_121'                                                                                                       
ptxas /tmp/tmpxft_000064a1_00000000-7_mmq-instance-mxfp4.ptx, line 112334; error   : Feature '.scale_vec::2X' not supported on .target 'sm_121'                                                                                                     
(many, many other similar lines)
```

I use a bash script on the DGX Spark to update and compile llama.cpp, it's always compiled the same way, so I'm confident it's something that was introduced.

**Comment by vektory79** [comment]
Sadly, for last commit (33 minutes ago) is not fix build for me:

```bash
cd llama.cpp
git pull
rm -r ./build
cmake \
    -B ./build \
    -DGGML_CUDA=ON \
    -DGGML_BLAS=OFF \
    -DGGML_NATIVE=ON \
    -DGGML_RPC=ON \
    -DGGML_BACKEND_DL=ON \
    -DGGML_CPU_ALL_VARIANTS=ON \
    -DCMAKE_CUDA_ARCHITECTURES="120" \
    -DGGML_CUDA_FA_ALL_QUANTS=true \
    -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
    -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release -j$(nproc --all)
```

I've same error for this script :(

**Comment by am17an** [comment]
I think the problem here is that you use GGML_NATIVE and CMAKE_CUDA_ARCHITECTURES, whereas the fix only applies to either. I will fix it, but for now you can either remove CMAKE_CUDA_ARCHITECTURES or use `120a` instead of 120

**Comment by vektory79** [comment]
I have:
- RTX 5090
- Ubuntu 24.04
- cmake version 3.28.3
- NVIDIA Driver Version: 590.48.01
- The CUDA compiler identification is NVIDIA 13.1.80

**Comment by vektory79** [comment]
> I think the problem here is that you use GGML_NATIVE and CMAKE_CUDA_ARCHITECTURES, whereas the fix only applies to either. I will fix it, but for now you can either remove CMAKE_CUDA_ARCHITECTURES or use `120a` instead of 120

Ok. Thanks a lot. I will test performance for that options combinations :)

**Comment by BahamutRU** [comment]
I use cuda 12.8, ubuntu 24.04, rtx 5060 ti with command:
```
cmake \
    -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLAMA_CURL=ON \
    -DGGML_CUDA=ON \
    -DGGML_VULKAN=OFF \
    -DGGML_RPC=OFF \
    -DGGML_BLAS=ON \
    -DGGML_BLAS_VENDOR=OpenBLAS \
    -DLLAMA_OPENSSL=ON \
    -DGGML_SCHED_MAX_COPIES=4 \
    -DGGML_CUDA_FA_ALL_QUANTS=ON \
    -DGGML_CCACHE=OFF
```
And get this error.

Then I use:
-DCMAKE_CUDA_ARCHITECTURES= …
120a
120a-real…
122f
122f-real

All of this version dropped an error.
```
-- Using CUDA architectures: 121f
CMake Error at /usr/share/cmake-3.28/Modules/Internal/CMakeCUDAArchitecturesValidate.cmake:9 (message):
  CMAKE_CUDA_ARCHITECTURES:

    121f

  is not one of the following:

    * a semicolon-separated list of integers, each optionally
      followed by '-real' or '-virtual'
    * a special value: all, all-major, native

Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/CMakeDetermineCUDACompiler.cmake:116 (cmake_cuda_architectures_validate)
  ggml/src/ggml-cuda/CMakeLists.txt:42 (enable_language)
```

And
-DCMAKE_CUDA_ARCHITECTURES= …
90
120
120-real

And again give classic error.
```
ptxas /tmp/tmpxft_0000973b_00000000-6_mmq-instance-mxfp4.ptx, line 122018; error   : Instruction 'mma with block scale' not supported on .target 'sm_120'
ptxas /tmp/tmpxft_0000973b_00000000-6_mmq-instance-mxfp4.ptx, line 122018; error   : Feature '.kind::mxf4' not supported on .target 'sm_120'
ptxas /tmp/tmpxft_0000973b_00000000-6_mmq-instance-mxfp4.ptx, line 122018; error   : Feature '.block_scale' not supported on .target 'sm_120'
ptxas /tmp/tmpxft_0000973b_00000000-6_mmq-instance-mxfp4.ptx, line 122018; error   : Feature '.scale_vec::2X' not supported on .target 'sm_120'
ptxas fatal   : Ptx assembly aborted due to errors
gmake[2]: *** [ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/build.make:1502: ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-mxfp4.cu.o] Ошибка 255
gmake[2]: *** Ожидание завершения заданий…
gmake[1]: *** [CMakeFiles/Makefile2:1926: ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/all] Ошибка 2
gmake: *** [Makefile:146: all] Ошибка 2
```

**Comment by am17an** [comment]
Can you confirm if this is  after #18361? If yes, please share full command that doesn't work for you

**Comment by vektory79** [comment]
Same here

```bash
cd llama.cpp
git pull
rm -r ./build
cmake \
    -B ./build \
    -DGGML_CUDA=ON \
    -DGGML_BLAS=OFF \
    -DGGML_NATIVE=OFF \
    -DGGML_RPC=ON \
    -DGGML_BACKEND_DL=ON \
    -DGGML_CPU_ALL_VARIANTS=ON \
    -DCMAKE_CUDA_ARCHITECTURES="120f" \
    -DGGML_CUDA_FA_ALL_QUANTS=true \
    -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
    -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release -j$(nproc --all)
```

And error:

```
-- Found CUDAToolkit: /usr/local/cuda/targets/x86_64-linux/include (found version "13.1.80") 
-- CUDA Toolkit found
-- Using CUDA architectures: 120f
CMake Error at /usr/share/cmake-3.28/Modules/Internal/CMakeCUDAArchitecturesValidate.cmake:9 (message):
  CMAKE_CUDA_ARCHITECTURES:

    120f

  is not one of the following:

    * a semicolon-separated list of integers, each optionally
      followed by '-real' or '-virtual'
    * a special value: all, all-major, native

Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/CMakeDetermineCUDACompiler.cmake:116 (cmake_cuda_architectures_validate)
  ggml/src/ggml-cuda/CMakeLists.txt:42 (enable_language)
```

**Comment by vektory79** [comment]
But:

```bash
cd llama.cpp
git pull
rm -r ./build
cmake \
    -B ./build \
    -DGGML_CUDA=ON \
    -DGGML_BLAS=OFF \
    -DGGML_NATIVE=OFF \
    -DGGML_RPC=ON \
    -DGGML_BACKEND_DL=ON \
    -DGGML_CPU_ALL_VARIANTS=ON \
    -DCMAKE_CUDA_ARCHITECTURES="120a" \
    -DGGML_CUDA_FA_ALL_QUANTS=true \
    -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
    -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release -j$(nproc --all)
```

works perfect...

**Comment by BahamutRU** [comment]
```
commit 83b3b1c271c78bd77664120431aa8c354d68daac (HEAD, origin/master, origin/HEAD)
Author: Aman Gupta <amangupta052@gmail.com>
Date:   Thu Dec 25 23:55:38 2025 +0800

    cuda: optimize cumsum cub path (#18362)

    * cuda: optimize cumsum cub path

    * remove heavy perf test

commit b0fb0f0aee2c931cbc08e95aef68f615c6de90a2 (tag: b7538, master)
Author: Aman Gupta <amangupta052@gmail.com>
Date:   Thu Dec 25 22:12:11 2025 +0800

    ggml-cuda: fix blackwell native builds (#18361)

    * ggml-cuda: fix blackwell native builds

    Replace 12x in native architectures by 12xa

    * replace for GGML_NATIVE=OFF too

    * only replace for native

    * remove 120f-virtual for default compilation

    ---------

    Co-authored-by: Aman Gupta <aman>

```

```
rm -rf build
cmake -B build -DCMAKE_BUILD_TYPE=Release -DLLAMA_CURL=ON -DGGML_CUDA=ON -DGGML_VULKAN=OFF -DGGML_RPC=OFF -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS -DGGML_CUDA_F16=ON -DLLAMA_OPENSSL=ON -DGGML_SCHED_MAX_COPIES=4 -DGGML_CUDA_FA_ALL_QUANTS=ON -DGGML_CCACHE=OFF -DCMAKE_CUDA_ARCHITECTURES=120f-real
-- The C compiler identification is GNU 13.3.0
-- The CXX compiler identification is GNU 13.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE=Release
-- Found Git: /usr/bin/git (found version "2.43.0")
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libopenblas.so
-- BLAS found, Libraries: /usr/lib/x86_64-linux-gnu/libopenblas.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1")
-- Checking for module 'openblas64'
--   Found openblas64, version 0.3.26
-- BLAS found, Includes: /usr/include/x86_64-linux-gnu/openblas64-pthread/
-- Including BLAS backend
-- Found CUDAToolkit: /usr/local/cuda-12.8/targets/x86_64-linux/include (found version "12.8.93")
-- CUDA Toolkit found
-- Using CUDA architectures: 120f-real
CMake Error at /usr/share/cmake-3.28/Modules/Internal/CMakeCUDAArchitecturesValidate.cmake:9 (message):
  CMAKE_CUDA_ARCHITECTURES:

    120f-real

  is not one of the following:

    * a semicolon-separated list of integers, each optionally
      followed by '-real' or '-virtual'
    * a special value: all, all-major, native

Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/CMakeDetermineCUDACompiler.cmake:116 (cmake_cuda_architectures_validate)
  ggml/src/ggml-cuda/CMakeLists.txt:42 (enable_language)


-- Configuring incomplete, errors occurred!

```

**Comment by am17an** [comment]
That's a CMake bug (it does not understand the `f` stuff). I think if you upgrade your CMake it should work

**Comment by am17an** [comment]
@BahamutRU either remove  `-DCMAKE_CUDA_ARCHITECTURES=120f-real` or use `-DCMAKE_CUDA_ARCHITECHTURES=120` (it's the same CMake bug)

**Comment by BahamutRU** [comment]
> works perfect...

Yeah, but…

> Ptx assembly aborted due to errors

=D

Lets update cmake…

**Comment by BahamutRU** [comment]
> [@BahamutRU](https://github.com/BahamutRU) either remove `-DCMAKE_CUDA_ARCHITECTURES=120f-real` or use `-DCMAKE_CUDA_ARCHITECHTURES=120` (it's the same CMake bug)

As I wrote above: Ptx assembly aborted due to errors with 120.

**Comment by BahamutRU** [comment]
```
-- Check for working CUDA compiler: /usr/local/cuda-12.8/bin/nvcc - broken
CMake Error at /opt/cmake-4.2.1-linux-x86_64/share/cmake-4.2/Modules/CMakeTestCUDACompiler.cmake:59 (message):
  The CUDA compiler

    "/usr/local/cuda-12.8/bin/nvcc"

  is not able to compile a simple test program.
```

Let's try update CUDA to 13.1…

**Comment by am17an** [comment]
@BahamutRU please create a separate issue with steps to reproduce and stop spamming this thread

**Comment by BahamutRU** [comment]
@am17an Why? This is exactly the same error.

Sry, no. =)

———

Updated CMake to version 4.2.1 and CUDA to version 13.1.
All previous errors disappeared (for 120a~121f-real), but the original one remains.
It says "not supported on .target 'sm_120'" for any specified architecture.

I'll update the drivers, I think.

**Comment by raziel2001au** [comment]
If people are stuck and unable to compile, it looks like setting GGML_NATIVE to OFF will get it built and get you back up and running again until this issue is resolved:
`cmake -B build -DGGML_CUDA=ON -DLLAMA_CURL=ON -DGGML_NATIVE=OFF`

As soon as GGML_NATIVE is ON, it seems to fail to compile with the errors I posted earlier on. Not sure what the side-effects of disabling this is, but at least it gets a person going again. Hopefully this issue will get sorted out soon.

If it helps, I'm building on DGX Spark, with CUDA 13.0 (sm_121) as that is what NVIDIA ships on the hardware. Installing weird versions of software wouldn't be an option here as NVIDIA maintains it via updates and such, I don't want to mess with it as everyone who's tried ended up making life more complicated for themselves (and everyone else when they post about it on the forums). I read something about a Cmake version, again, this is pre-installed by NVIDIA, not going to mess with what's installed on the system.

**Comment by am17an** [comment]
@raziel2001au did you get an error on the latest master?

**Comment by raziel2001au** [comment]
> [@raziel2001au](https://github.com/raziel2001au) did you get an error on the latest master?

Yes, I just updated to the latest master after reading your message, if I don't pass -DGGML_NATIVE=OFF it fails to compile as below:
```
ptxas /tmp/tmpxft_0000ef4d_00000000-6_mmq-instance-mxfp4.ptx, line 123423; error   : Feature '.kind::mxf4' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000ef4d_00000000-6_mmq-instance-mxfp4.ptx, line 123423; error   : Feature '.block_scale' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000ef4d_00000000-6_mmq-instance-mxfp4.ptx, line 123423; error   : Feature '.scale_vec::2X' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000ef4d_00000000-6_mmq-instance-mxfp4.ptx, line 123437; error   : Instruction 'mma with block scale' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000ef4d_00000000-6_mmq-instance-mxfp4.ptx, line 123437; error   : Feature '.kind::mxf4' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000ef4d_00000000-6_mmq-instance-mxfp4.ptx, line 123437; error   : Feature '.block_scale' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000ef4d_00000000-6_mmq-instance-mxfp4.ptx, line 123437; error   : Feature '.scale_vec::2X' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000ef4d_00000000-6_mmq-instance-mxfp4.ptx, line 123447; error   : Instruction 'mma with block scale' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000ef4d_00000000-6_mmq-instance-mxfp4.ptx, line 123447; error   : Feature '.kind::mxf4' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000ef4d_00000000-6_mmq-instance-mxfp4.ptx, line 123447; error   : Feature '.block_scale' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000ef4d_00000000-6_mmq-instance-mxfp4.ptx, line 123447; error   : Feature '.scale_vec::2X' not supported on .target 'sm_121'
ptxas fatal   : Ptx assembly aborted due to errors
gmake[2]: *** [ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/build.make:1502: ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-mxfp4.cu.o] Error 255
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:1881: ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

**Comment by BahamutRU** [comment]
Thx @raziel2001au , work with -DGGML_NATIVE=OFF

**Comment by vektory79** [comment]
Auch!!! On last commit I have a crash!

Build:

```bash
cd llama.cpp
git pull
rm -r ./build
cmake \
    -B ./build \
    -DGGML_CUDA=ON \
    -DGGML_BLAS=OFF \
    -DGGML_NATIVE=OFF \
    -DGGML_RPC=ON \
    -DGGML_BACKEND_DL=ON \
    -DGGML_CPU_ALL_VARIANTS=ON \
    -DCMAKE_CUDA_ARCHITECTURES="120a" \
    -DGGML_CUDA_FA_ALL_QUANTS=true \
    -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
    -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release -j$(nproc --all)
```

Run:

```bash
MODEL="unsloth/Qwen3-235B-A22B-Instruct-2507-GGUF/Q3_K_M/Qwen3-235B-A22B-Instruct-2507-Q3_K_M.gguf"
./llama.cpp/build/bin/llama-bench \
    --model $MODEL \
    --repetitions 25 \
    --delay 5 \
    --n-prompt 512 \
    --n-gen 512 \
    --flash-attn 1 \
    --ubatch-size 4096 \
    --cache-type-k q8_0 \
    --cache-type-v f16 \
    --override-tensor exps=CPU \
    --n-gpu-layers 999 \
    --cpu-mask 0xFFFF \
    --threads 16
```

Get a crash:
```
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 5090, compute capability 12.0, VMM: yes
load_backend: loaded CUDA backend from /media/ai/hf/llama.cpp/build/bin/libggml-cuda.so
load_backend: loaded RPC backend from /media/ai/hf/llama.cpp/build/bin/libggml-rpc.so
load_backend: loaded CPU backend from /media/ai/hf/llama.cpp/build/bin/libggml-cpu-alderlake.so
| model                          |       size |     params | backend    | ngl | threads | cpu_mask   | n_ubatch | type_k | fa | ot                    |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------: | ---------- | -------: | -----: | -: | --------------------- | --------------: | -------------------: |
/media/ai/hf/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:94: CUDA error
[New LWP 405326]
[New LWP 405325]
[New LWP 405324]
[New LWP 405320]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007faa90f10813 in __GI___wait4 (pid=405408, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
warning: 30     ../sysdeps/unix/sysv/linux/wait4.c: Нет такого файла или каталога
#0  0x00007faa90f10813 in __GI___wait4 (pid=405408, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x00007faa919046b3 in ggml_print_backtrace () from /media/ai/hf/llama.cpp/build/bin/libggml-base.so.0
#2  0x00007faa9190485b in ggml_abort () from /media/ai/hf/llama.cpp/build/bin/libggml-base.so.0
#3  0x00007faa8f9916a7 in ggml_cuda_error(char const*, char const*, char const*, int, char const*) () from /media/ai/hf/llama.cpp/build/bin/libggml-cuda.so
#4  0x00007faa8f9b9b55 in ggml_cuda_mul_mat_q(ggml_backend_cuda_context&, ggml_tensor const*, ggml_tensor const*, ggml_tensor const*, ggml_tensor*) () from /media/ai/hf/llama.cpp/build/bin/libggml-cuda.so
#5  0x00007faa8f9a2e4c in ggml_cuda_compute_forward(ggml_backend_cuda_context&, ggml_tensor*) () from /media/ai/hf/llama.cpp/build/bin/libggml-cuda.so
#6  0x00007faa8f9a6e53 in evaluate_and_capture_cuda_graph(ggml_backend_cuda_context*, ggml_cgraph*, bool&, bool&, bool&) [clone .constprop.0] () from /media/ai/hf/llama.cpp/build/bin/libggml-cuda.so
#7  0x00007faa8f9a8fac in ggml_backend_cuda_graph_compute(ggml_backend*, ggml_cgraph*) () from /media/ai/hf/llama.cpp/build/bin/libggml-cuda.so
#8  0x00007faa919209a7 in ggml_backend_sched_graph_compute_async () from /media/ai/hf/llama.cpp/build/bin/libggml-base.so.0
#9  0x00007faa916b0291 in llama_context::graph_compute(ggml_cgraph*, bool) () from /media/ai/hf/llama.cpp/build/bin/libllama.so.0
#10 0x00007faa916b1b31 in llama_context::process_ubatch(llama_ubatch const&, llm_graph_type, llama_memory_context_i*, ggml_status&) () from /media/ai/hf/llama.cpp/build/bin/libllama.so.0
#11 0x00007faa916b85f7 in llama_context::decode(llama_batch const&) () from /media/ai/hf/llama.cpp/build/bin/libllama.so.0
#12 0x00007faa916b950f in llama_decode () from /media/ai/hf/llama.cpp/build/bin/libllama.so.0
#13 0x00005f7960ad8ff1 in test_prompt(llama_context*, int, int, int) ()
#14 0x00005f7960ad4e17 in main ()
[Inferior 1 (process 405319) detached]
```

Some commits before its run perfectly with exact build and run parameters...

**Comment by vektory79** [comment]
Seems, that this is because of cmake 4.2.1, that I setup recently...

**Comment by vektory79** [comment]
Yes. I revert cmake to version 3.28.3 and this error gone...

**Comment by raziel2001au** [comment]
I pulled the latest code this morning and it now builds successfully without additional parameters. So, does this include the native support for mxfp4 now or is it just detecting there'd be a compile issue and silently disables the feature (i.e. its this build equivalent to -DGGML_NATIVE=OFF or should it be working now)?

Also, not sure if this is useful for anyone, but since there's been some talk around CMake versions, I thought I'd mention the DGX Spark (what I'm building on) currently includes CMake version 3.28.3.

**Comment by am17an** [comment]
Yes it should be fixed now, it should include the mxfp4 acceleration

**Comment by isgallagher** [comment]
Anyone running with these like I was, be sure to remove them:

```
-DCMAKE_CXX_FLAGS=-march=native -DCMAKE_CUDA_FLAGS=-arch=native
```

**Comment by phaelon74** [comment]
> You need to add `120a`, or use [#18361](https://github.com/ggml-org/llama.cpp/pull/18361)

My apologies, but why was sm120 broken for this change?  It no longer works at all now? Are there multiple branches of sm120 where you need to distinguish them?

**Comment by am17an** [comment]
@phaelon74 not sure what you're asking but there is no need to specify anything on the latest master now. If you still have problems please create an issue with the exact command which fails for you.

**Comment by phaelon74** [comment]
> [@phaelon74](https://github.com/phaelon74) not sure what you're asking but there is no need to specify anything on the latest master now. If you still have problems please create an issue with the exact command which fails for you.

I want it to only build sm120, and thus when I specify that, it breaks.  I'm not a fan of letting the system decide what architecture I have.

**Comment by raziel2001au** [comment]
It was working, but it seems like this issue has been reintroduced, I updated the code today, and now I'm getting this:
```
ptxas /tmp/tmpxft_0000802e_00000000-7_mmq-instance-mxfp4.ptx, line 123423; error   : Feature '.block_scale' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000802e_00000000-7_mmq-instance-mxfp4.ptx, line 123423; error   : Feature '.scale_vec::2X' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000802e_00000000-7_mmq-instance-mxfp4.ptx, line 123437; error   : Instruction 'mma with block scale' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000802e_00000000-7_mmq-instance-mxfp4.ptx, line 123437; error   : Feature '.kind::mxf4' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000802e_00000000-7_mmq-instance-mxfp4.ptx, line 123437; error   : Feature '.block_scale' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000802e_00000000-7_mmq-instance-mxfp4.ptx, line 123437; error   : Feature '.scale_vec::2X' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000802e_00000000-7_mmq-instance-mxfp4.ptx, line 123447; error   : Instruction 'mma with block scale' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000802e_00000000-7_mmq-instance-mxfp4.ptx, line 123447; error   : Feature '.kind::mxf4' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000802e_00000000-7_mmq-instance-mxfp4.ptx, line 123447; error   : Feature '.block_scale' not supported on .target 'sm_121'
ptxas /tmp/tmpxft_0000802e_00000000-7_mmq-instance-mxfp4.ptx, line 123447; error   : Feature '.scale_vec::2X' not supported on .target 'sm_121'
```

**Comment by uis246** [comment]
> Yes it should be fixed now, it should include the mxfp4 acceleration

No, it's not. I still cannot compile with all-major, which includes Blackwell.
